import 'package:flutter/material.dart';
import 'package:sunamonir_pathshala/components/english/sentence_listtile.dart';
import 'package:sunamonir_pathshala/utils/audios/audios.dart';
import 'package:sunamonir_pathshala/utils/text_string/string_constant.dart';

class SentenceMaking extends StatelessWidget {
  const SentenceMaking({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: const Color(0xffffffff),
        appBar: AppBar(
          elevation: 5,
          iconTheme: const IconThemeData(color: Colors.white),
          title: const Text(
            'Sentence Making',
            style: TextStyle(
              fontFamily: StringConstants.enFontFamily,
              fontWeight: FontWeight.w600,
              color: Colors.white,
            ),
          ),
          backgroundColor: const Color(0xff1b374f),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                decoration: BoxDecoration(
                  color: const Color(0xff444444),
                  borderRadius: BorderRadius.circular(5.0),
                ),
                margin: const EdgeInsets.symmetric(vertical: 10, horizontal: 10),
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Row(
                    children: [
                      Container(
                        height: 25,
                        width: 6,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(10),
                          color: const Color(0xffe04a84),
                        ),
                      ),
                      const SizedBox(width: 8),
                      const Expanded(
                        child: Text(
                          'Making Sentence with Letters',
                          style: TextStyle(
                            fontSize: 18,
                            fontFamily: StringConstants.enFontFamily,
                            fontWeight: FontWeight.w600,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'A',
                title1: 'As a result',
                title2: 'At any cost',
                title3: 'Anything else?',
                title4: 'Anika goes to school',
                title5: 'A lion is a wild animal',
                subtitle1: 'এর ফলে।',
                subtitle2: 'যে কোনো মূল্যে।',
                subtitle3: 'আর কিছু?',
                subtitle4: 'আনিকা স্কুলে যায়।',
                subtitle5: 'সিংহ একটি বন্য প্রাণী।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'B',
                title1: 'The ball is round',
                title2: 'The baby is crying',
                title3: 'Birds fly in the sky',
                title4: 'The boat is on the river',
                title5: 'This is my school bag',
                subtitle1: 'বলটি গোল।',
                subtitle2: 'শিশুটি কাঁদছে।',
                subtitle3: 'পাখিরা আকাশে উড়ে।',
                subtitle4: 'নৌকাটি নদীতে আছে।',
                subtitle5: 'এটি আমার স্কুল ব্যাগ।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'C',
                title1: 'Close your books',
                title2: 'Clean up the room',
                title3: 'Copy the word',
                title4: 'Come in',
                title5: 'The Candle is burning',
                subtitle1: 'তোমার বই বন্ধ কর।',
                subtitle2: 'রুমটা পরিষ্কার কর।',
                subtitle3: 'শব্দটি নকল কর।',
                subtitle4: 'ভেতরে এসাে।',
                subtitle5: 'মোমবাতিটি জ্বলছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'D',
                title1: 'Draw a picture',
                title2: 'Did you get it?',
                title3: 'Don’t worry',
                title4: 'Don’t be lazy',
                title5: 'Don’t forget',
                subtitle1: 'একটি ছবি আঁক।',
                subtitle2: 'তুমি কি বুঝতে পেরেছ?',
                subtitle3: 'চিন্তা করবে না।',
                subtitle4: 'আলস হবে না।',
                subtitle5: 'ভুলবে না।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'E',
                title1: 'Elephants are big animals',
                title2: 'Exercise makes us strong',
                title3: 'Earth is our home.',
                title4: 'Elephants have big ears',
                title5: 'Exercise makes us strong',
                subtitle1: 'হাতি খুব বড় প্রাণী।',
                subtitle2: 'ব্যায়াম করলে শরীর শক্ত হয়।',
                subtitle3: 'পৃথিবী আমাদের বাড়ি।',
                subtitle4: 'হাতির বড় বড় কান থাকে।',
                subtitle5: 'ব্যায়াম আমাদের শক্তিশালী করে তোলে',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'F',
                title1: 'The flowers smell sweet',
                title2: 'Fish live in the water',
                title3: 'Frogs jump high.',
                title4: 'Food gives us energy.',
                title5: 'The fox is very quick.',
                subtitle1: 'ফুলগুলোর গন্ধ খুব মিষ্টি।',
                subtitle2: 'মাছ পানিতে থাকে।',
                subtitle3: 'ব্যাঙ অনেক উঁচুতে লাফায়।',
                subtitle4: 'খাবার আমাদের শক্তি দেয়।',
                subtitle5: 'শিয়াল খুব দ্রুত।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'G',
                title1: 'Go to school',
                title2: 'Giraffes are tall.',
                title3: 'Gardens have flowers.',
                title4: 'Gold is a precious metal.',
                title5: 'Grapes are sweet.',
                subtitle1: 'স্কুলে যাও।',
                subtitle2: 'জিরাফ লম্বা।',
                subtitle3: 'বাগানে ফুল থাকে।',
                subtitle4: 'সোনা একটি মূল্যবান ধাতু।',
                subtitle5: 'আঙুর মিষ্টি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'H',
                title1: 'He is my friend.',
                title2: 'Her dress is beautiful.',
                title3: 'Horses run fast.',
                title4: 'Honey is sweet.',
                title5: 'Help others in need.',
                subtitle1: 'সে আমার বন্ধু।',
                subtitle2: 'তার পোশাক সুন্দর।',
                subtitle3: 'ঘোড়া দ্রুত দৌড়ায়।',
                subtitle4: 'মধু মিষ্টি।',
                subtitle5: 'অন্যদের সাহায্য কর।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'I',
                title1: 'I am happy',
                title2: 'I am learning English.',
                title3: 'I love my family.',
                title4: 'I like ice cream.',
                title5: 'I play with my friends.',
                subtitle1: 'আমি খুশি।',
                subtitle2: 'আমি ইংরেজি শিখছি।',
                subtitle3: 'আমি আমার পরিবারকে ভালোবাসি।',
                subtitle4: 'আমি আইসক্রিম পছন্দ করি।',
                subtitle5: 'আমি আমার বন্ধুদের সঙ্গে খেলি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'J',
                title1: 'Jump over the rope.',
                title2: 'Jenny loves to draw.',
                title3: 'John has a red car.',
                title4: 'Juice is tasty and healthy.',
                title5: 'Jasmine is a lovely flower.',
                subtitle1: 'দড়ির উপর দিয়ে লাফ দাও।',
                subtitle2: 'জেনি আঁকতে ভালোবাসে।',
                subtitle3: 'জনের একটি লাল গাড়ি আছে।',
                subtitle4: 'জুস সুস্বাদু এবং স্বাস্থ্যকর।',
                subtitle5: 'জুঁই একটি সুন্দর ফুল।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'K',
                title1: 'Kids love to play.',
                title2: 'Keep your room clean.',
                title3: 'Kangaroos can jump far.',
                title4: 'Kindness is a great virtue.',
                title5: 'Keep your hands clean.',
                subtitle1: 'বাচ্চারা খেলতে ভালোবাসে।',
                subtitle2: 'তোমার ঘর পরিষ্কার রাখো।',
                subtitle3: 'ক্যাঙ্গারু অনেক দূর লাফাতে পারে।',
                subtitle4: 'দয়া একটি মহৎ গুণ।',
                subtitle5: 'তোমার হাত পরিষ্কার রাখো।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'L',
                title1: 'Lions live in the jungle.',
                title2: 'Lucy likes to dance.',
                title3: 'Lemons are sour.',
                title4: 'Leaves fall in autumn.',
                title5: 'Lets play in the park.',
                subtitle1: 'সিংহ জঙ্গলে বাস করে।',
                subtitle2: 'লুসি নাচতে পছন্দ করে।',
                subtitle3: 'লেবু টক।',
                subtitle4: 'শীতে পাতা ঝরে।',
                subtitle5: 'চলো পার্কে খেলি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'M',
                title1: 'Milk is good for health.',
                title2: 'Mountains are very tall.',
                title3: 'Music makes me happy.',
                title4: 'Mangoes are sweet and juicy.',
                title5: 'Monkeys swing on trees.',
                subtitle1: 'দুধ স্বাস্থ্যকর।',
                subtitle2: 'পাহাড়গুলো অনেক উঁচু।',
                subtitle3: 'সঙ্গীত আমাকে খুশি করে।',
                subtitle4: 'আম মিষ্টি এবং রসালো।',
                subtitle5: 'বানর গাছে দোল খায়।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'N',
                title1: 'Never tell a lie.',
                title2: 'New books smell nice.',
                title3: 'Nobody likes to be sad.',
                title4: 'Night is dark and quiet.',
                title5: 'I like to eat noodles.',
                subtitle1: 'কখনো মিথ্যা বলবে না।',
                subtitle2: 'নতুন বইয়ের গন্ধ ভালো।',
                subtitle3: 'কেউ দুঃখী হতে চায় না।',
                subtitle4: 'রাত অন্ধকার এবং শান্ত।',
                subtitle5: 'আমি নুডলস খেতে পছন্দ করি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'O',
                title1: 'Owls fly at night.',
                title2: 'Orange is my favorite color.',
                title3: 'Open the door, please.',
                title4: 'I like to eat oranges.',
                title5: 'The octopus has eight arms.',
                subtitle1: 'পেঁচাগুলো রাতে উড়ে।',
                subtitle2: 'কমলা আমার প্রিয় রঙ।',
                subtitle3: 'দয়া করে দরজা খুলো।',
                subtitle4: 'আমি কমলা খেতে পছন্দ করি।',
                subtitle5: 'অক্টোপাসের আটটি হাত রয়েছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'p',
                title1: 'Puppies are very cute.',
                title2: 'Pink is a pretty color.',
                title3: 'I have a pencil in my bag.',
                title4: 'Peacocks have beautiful feathers.',
                title5: 'Pineapples are sweet and sour.',
                subtitle1: 'কুকুরছানা খুব সুন্দর।',
                subtitle2: 'গোলাপী একটি সুন্দর রঙ।',
                subtitle3: 'আমার ব্যাগে একটি পেন্সিল আছে।',
                subtitle4: 'ময়ূরের সুন্দর পালক থাকে।',
                subtitle5: 'আনারস মিষ্টি এবং টক।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'Q',
                title1: 'Queen is a kind ruler.',
                title2: 'The quiz is fun.',
                title3: 'Quiet please, I am reading.',
                title4: 'The quail is a small bird.',
                title5: 'I have a question.',
                subtitle1: 'রাণী একটি দয়ালু শাসক।',
                subtitle2: 'কুইজ মজা।',
                subtitle3: 'দয়া করে চুপ থাকো, আমি পড়ছি।',
                subtitle4: 'কোয়েল একটি ছোট পাখি।',
                subtitle5: 'আমার একটি প্রশ্ন আছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'R',
                title1: 'Roses are beautiful flowers.',
                title2: 'Rocks are hard and heavy.',
                title3: 'Read your favorite book.',
                title4: 'Rats live in the dark.',
                title5: 'The rainbow has many colors.',
                subtitle1: 'গোলাপ সুন্দর ফুল।',
                subtitle2: 'পাথর শক্ত এবং ভারী।',
                subtitle3: 'তোমার প্রিয় বইটি পড়ো।',
                subtitle4: 'ইঁদুররা অন্ধকারে থাকে।',
                subtitle5: 'রংধনুর অনেক রঙ রয়েছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'S',
                title1: 'She is my best friend.',
                title2: 'Sunsets are beautiful.',
                title3: 'The sun is shining.',
                title4: 'The ship sails on the sea.',
                title5: 'She sings a lovely song.',
                subtitle1: 'সে আমার সবচেয়ে ভালো বন্ধু।',
                subtitle2: 'সূর্যাস্ত সুন্দর।',
                subtitle3: 'সূর্য উজ্জ্বলভাবে আলো ছড়াচ্ছে।',
                subtitle4: 'জাহাজ সাগরে চলে।',
                subtitle5: 'সে একটি সুন্দর গান গায়।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'T',
                title1: 'The tiger is strong.',
                title2: 'The turtle is slow.',
                title3: 'The tree is very tall.',
                title4: 'The train is coming.',
                title5: 'Tigers live in the jungle.',
                subtitle1: 'বাঘ শক্তিশালী।',
                subtitle2: 'কচ্ছপ ধীর।',
                subtitle3: 'গাছটি অনেক উঁচু।',
                subtitle4: 'ট্রেন আসছে।',
                subtitle5: 'বাঘ জঙ্গলে বাস করে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'U',
                title1: 'The umbrella keeps me dry.',
                title2: 'The tree grows up every year.',
                title3: 'I have an umbrella.',
                title4: 'Under the tree, there is a bench.',
                title5: 'Unicorns are magical creatures.',
                subtitle1: 'ছাতা আমাকে শুকনো রাখে।',
                subtitle2: 'গাছটি প্রতি বছর বাড়ে।',
                subtitle3: 'আমার একটি ছাতা আছে।',
                subtitle4: 'গাছের নিচে একটি বেঞ্চ আছে।',
                subtitle5: 'ইউনিকর্ন হল জাদুকরী প্রাণী।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'V',
                title1: 'Violet is a beautiful color.',
                title2: 'Vegetables are healthy for us.',
                title3: 'I like to eat vegetables.',
                title4: 'The violin makes beautiful music.',
                title5: 'The volcano is erupting.',
                subtitle1: 'বেগুনি একটি সুন্দর রঙ।',
                subtitle2: 'সবজি আমাদের জন্য স্বাস্থ্যকর।',
                subtitle3: 'আমি সবজি খেতে পছন্দ করি।',
                subtitle4: 'ভায়োলিন সুন্দর সঙ্গীত তৈরি করে।',
                subtitle5: 'আগ্নেয়গিরি উদগীরণ করছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'W',
                title1: 'Water is good for our health.',
                title2: 'Waking up early is good for you.',
                title3: 'We are going to the park.',
                title4: 'Wolves live in the forest.',
                title5: 'The wind is blowing fast.',
                subtitle1: 'পানি আমাদের স্বাস্থ্য জন্য ভালো।',
                subtitle2: 'সকাল সকাল ওঠা তোমার জন্য ভালো।',
                subtitle3: 'আমরা পার্কে যাচ্ছি।',
                subtitle4: 'নেকড়েরা জঙ্গলে বাস করে।',
                subtitle5: 'হাওয়া দ্রুত বইছে।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'X',
                title1: 'The x-ray shows the broken bone.',
                title2: 'Xenops are small birds in the jungle.',
                title3: 'The letter X is in the middle of "box."',
                title4: 'The xylophone makes music.',
                title5: 'I like the letter X.',
                subtitle1: 'এক্স-রে ভাঙা হাড় দেখায়।',
                subtitle2: 'জেনোপস হল জঙ্গলে ছোট পাখি।',
                subtitle3: 'বক্স শব্দটির মাঝখানে X আছে।',
                subtitle4: 'জাইলোফোন সঙ্গীত তৈরি করে।',
                subtitle5: 'আমি X অক্ষরটি পছন্দ করি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'Y',
                title1: 'Yellow is a bright color.',
                title2: 'I like to eat yogurt.',
                title3: 'Yogurt is delicious and healthy.',
                title4: 'The young bird is learning to fly.',
                title5: 'I like to eat yellow bananas.',
                subtitle1: ' হলুদ একটি উজ্জ্বল রঙ।',
                subtitle2: 'আমি দই খেতে পছন্দ করি।',
                subtitle3: 'দই সুস্বাদু এবং স্বাস্থ্যকর।',
                subtitle4: 'তরুণ পাখিটি উড়তে শিখছে।',
                subtitle5: 'আমি হলুদ কলা খেতে পছন্দ করি।',
              ),
              SentenceTile(
                audioUrl: AudioConstant.bAudio1,
                letter: 'Z',
                title1: 'The zebra is running fast.',
                title2: 'The zoo has many animals.',
                title3: 'Zebras live in Africa.',
                title4: 'I saw a zebra at the zoo.',
                title5: 'Zebras are wild animals.',
                subtitle1: 'জেব্রা দ্রুত দৌড়াচ্ছে।',
                subtitle2: 'চিড়িয়াখানায় অনেক প্রাণী আছে।',
                subtitle3: 'জেব্রারা আফ্রিকায় বাস করে।',
                subtitle4: 'আমি চিড়িয়াখানায় একটি জেব্রা দেখেছি।',
                subtitle5: 'জেব্রারা বন্য প্রাণী।',
              ),
            ],
          ),
        ));
  }
}
