import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'package:sunamonir_pathshala/ads/native_ads_widget.dart';
import 'package:sunamonir_pathshala/base_scaffold.dart';
import 'package:sunamonir_pathshala/components/mathematics/multiplication_card.dart';
import 'package:sunamonir_pathshala/services/ads_helper.dart';
import 'package:sunamonir_pathshala/utils/audios/audios.dart';
import 'package:sunamonir_pathshala/utils/text_string/string_constant.dart';

class MultiplicationTable extends StatelessWidget {
  MultiplicationTable({super.key});

  final player = AudioPlayer();

  @override
  Widget build(BuildContext context) {
    return AdScaffold(
      appBar: AppBar(
        title: const Text(
          'গুণের নামতা (১ থেকে ২০) পর্যন্ত',
          style: TextStyle(
            color: Colors.white,
            fontFamily: StringConstants.skBishal,
          ),
        ),
        iconTheme: const IconThemeData(color: Colors.white),
        elevation: 0,
        backgroundColor: const Color(0xff343232),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            MultiplicationTableCard(
              multi_1: StringConstants.mOne1,
              multi_2: StringConstants.mOne2,
              multi_3: StringConstants.mOne3,
              multi_4: StringConstants.mOne4,
              multi_5: StringConstants.mOne5,
              multi_6: StringConstants.mOne6,
              multi_7: StringConstants.mOne7,
              multi_8: StringConstants.mOne8,
              multi_9: StringConstants.mOne9,
              multi_10: StringConstants.mOne10,
              bgColor: const Color(0xff404044),
              headerColor: const Color(0xffEC4A71),
              multiBarColor: const Color(0xff545050),
              multiBarTxtColor: const Color(0xff00A8FF),
              headerText: '১ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio1,
            ),
            Padding(
              padding: const EdgeInsets.only(left: 16.0, right: 16.0),
              child: NativeAdWidget(adUnitId: AdHelper.nativeAdUnitId, adSize: NativeAdSize.small),
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m2_1,
              multi_2: StringConstants.m2_2,
              multi_3: StringConstants.m2_3,
              multi_4: StringConstants.m2_4,
              multi_5: StringConstants.m2_5,
              multi_6: StringConstants.m2_6,
              multi_7: StringConstants.m2_7,
              multi_8: StringConstants.m2_8,
              multi_9: StringConstants.m2_9,
              multi_10: StringConstants.m2_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xff134B70),
              multiBarColor: const Color(0xff1A8888),
              multiBarTxtColor: const Color(0xffffffff),
              headerText: '২ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio2,
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m3_1,
              multi_2: StringConstants.m3_2,
              multi_3: StringConstants.m3_3,
              multi_4: StringConstants.m3_4,
              multi_5: StringConstants.m3_5,
              multi_6: StringConstants.m3_6,
              multi_7: StringConstants.m3_7,
              multi_8: StringConstants.m3_8,
              multi_9: StringConstants.m3_9,
              multi_10: StringConstants.m3_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xffBA68C8),
              multiBarColor: const Color(0xffAD7474),
              multiBarTxtColor: const Color(0xffFFD499),
              headerText: '৩ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio2,
            ),
            Padding(
              padding: const EdgeInsets.only(left: 16.0, right: 16.0),
              child: NativeAdWidget(adUnitId: AdHelper.nativeAdUnitId, adSize: NativeAdSize.small),
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m4_1,
              multi_2: StringConstants.m4_2,
              multi_3: StringConstants.m4_3,
              multi_4: StringConstants.m4_4,
              multi_5: StringConstants.m4_5,
              multi_6: StringConstants.m4_6,
              multi_7: StringConstants.m4_7,
              multi_8: StringConstants.m4_8,
              multi_9: StringConstants.m4_9,
              multi_10: StringConstants.m4_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xffFFE3D6),
              multiBarColor: const Color(0xff6482AD),
              multiBarTxtColor: const Color(0xffF2DDD3),
              headerText: '৪ এর গুণের নামতা',
              headerTextColor: const Color(0xff497AC1),
              audioString: AudioConstant.bAudio2,
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m5_1,
              multi_2: StringConstants.m5_2,
              multi_3: StringConstants.m5_3,
              multi_4: StringConstants.m5_4,
              multi_5: StringConstants.m5_5,
              multi_6: StringConstants.m5_6,
              multi_7: StringConstants.m5_7,
              multi_8: StringConstants.m5_8,
              multi_9: StringConstants.m5_9,
              multi_10: StringConstants.m5_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xff96CEB4),
              multiBarColor: const Color(0xffBB6EC8),
              multiBarTxtColor: const Color(0xffF9FFFC),
              headerText: '৫ এর গুণের নামতা',
              headerTextColor: const Color(0xff00040B),
              audioString: AudioConstant.bAudio2,
            ),
            Padding(
              padding: const EdgeInsets.only(left: 16.0, right: 16.0),
              child: NativeAdWidget(adUnitId: AdHelper.nativeAdUnitId, adSize: NativeAdSize.small),
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m6_1,
              multi_2: StringConstants.m6_2,
              multi_3: StringConstants.m6_3,
              multi_4: StringConstants.m6_4,
              multi_5: StringConstants.m6_5,
              multi_6: StringConstants.m6_6,
              multi_7: StringConstants.m6_7,
              multi_8: StringConstants.m6_8,
              multi_9: StringConstants.m6_9,
              multi_10: StringConstants.m6_10,
              bgColor: const Color(0xffDEF9C4),
              headerColor: const Color(0xff468585),
              multiBarColor: const Color(0xff9CDBA6),
              multiBarTxtColor: const Color(0xff046060),
              headerText: '৬ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio2,
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m7_1,
              multi_2: StringConstants.m7_2,
              multi_3: StringConstants.m7_3,
              multi_4: StringConstants.m7_4,
              multi_5: StringConstants.m7_5,
              multi_6: StringConstants.m7_6,
              multi_7: StringConstants.m7_7,
              multi_8: StringConstants.m7_8,
              multi_9: StringConstants.m7_9,
              multi_10: StringConstants.m7_10,
              bgColor: const Color(0xffF3B57C),
              headerColor: const Color(0xff2A629A),
              multiBarColor: const Color(0xffFFD499),
              multiBarTxtColor: const Color(0xff000000),
              headerText: '৭ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio2,
            ),
            Padding(
              padding: const EdgeInsets.only(left: 16.0, right: 16.0),
              child: NativeAdWidget(adUnitId: AdHelper.nativeAdUnitId, adSize: NativeAdSize.small),
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m8_1,
              multi_2: StringConstants.m8_2,
              multi_3: StringConstants.m8_3,
              multi_4: StringConstants.m8_4,
              multi_5: StringConstants.m8_5,
              multi_6: StringConstants.m8_6,
              multi_7: StringConstants.m8_7,
              multi_8: StringConstants.m8_8,
              multi_9: StringConstants.m8_9,
              multi_10: StringConstants.m8_10,
              bgColor: const Color(0xff8AC2E1),
              headerColor: const Color(0xff5B99C2),
              multiBarColor: const Color(0xff5B99C2),
              multiBarTxtColor: const Color(0xffFFE712),
              headerText: '৮ এর গুণের নামতা',
              headerTextColor: const Color(0xffffffff),
              audioString: AudioConstant.bAudio2,
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m9_1,
              multi_2: StringConstants.m9_2,
              multi_3: StringConstants.m9_3,
              multi_4: StringConstants.m9_4,
              multi_5: StringConstants.m9_5,
              multi_6: StringConstants.m9_6,
              multi_7: StringConstants.m9_7,
              multi_8: StringConstants.m9_8,
              multi_9: StringConstants.m9_9,
              multi_10: StringConstants.m9_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xffFFE3D6),
              multiBarColor: const Color(0xff6482AD),
              multiBarTxtColor: const Color(0xffF2DDD3),
              headerText: '৯ এর গুণের নামতা',
              headerTextColor: const Color(0xff497AC1),
              audioString: AudioConstant.bAudio2,
            ),
            Padding(
              padding: const EdgeInsets.only(left: 16.0, right: 16.0),
              child: NativeAdWidget(adUnitId: AdHelper.nativeAdUnitId, adSize: NativeAdSize.small),
            ),
            MultiplicationTableCard(
              multi_1: StringConstants.m10_1,
              multi_2: StringConstants.m10_2,
              multi_3: StringConstants.m10_3,
              multi_4: StringConstants.m10_4,
              multi_5: StringConstants.m10_5,
              multi_6: StringConstants.m10_6,
              multi_7: StringConstants.m10_7,
              multi_8: StringConstants.m10_8,
              multi_9: StringConstants.m10_9,
              multi_10: StringConstants.m10_10,
              bgColor: const Color(0xff666570),
              headerColor: const Color(0xff00C569),
              multiBarColor: const Color(0xff916D97),
              multiBarTxtColor: const Color(0xff3FFF20),
              headerText: '১০ এর গুণের নামতা',
              headerTextColor: const Color(0xff011E48),
              audioString: AudioConstant.bAudio2,
            ),
          ],
        ),
      ),
    );
  }
}
